"""add unique constraints to organizations

Revision ID: 6d0550c50f93
Revises: 6fcdc92def36
Create Date: 2026-06-07 18:28:50.373001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d0550c50f93'
down_revision: Union[str, Sequence[str], None] = '6fcdc92def36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'trade_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('organizations', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('organizations', 'tax_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'organizations', ['tax_id'])
    op.create_unique_constraint(None, 'organizations', ['contact_phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'organizations', type_='unique')
    op.alter_column('organizations', 'tax_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('organizations', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('organizations', 'trade_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
