"""update organizations table

Revision ID: 6fcdc92def36
Revises: eced291ccbe9
Create Date: 2026-06-07 17:27:17.179311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fcdc92def36'
down_revision: Union[str, Sequence[str], None] = 'eced291ccbe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('trade_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('tax_id', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(length=100), nullable=True))
    op.drop_column('organizations', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'department')
    op.drop_column('organizations', 'address')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'tax_id')
    op.drop_column('organizations', 'business_name')
    op.drop_column('organizations', 'trade_name')
    # ### end Alembic commands ###
